### ISSUE TITLE
Object as parameter

### ISSUE THREAD

**Issue by EldonMcGuinness** [alfg/ping.js#11]
With the list of parameters growing it might be prudent to allow a built object to be passed into the ping call.

Ex.

```
{
    "host" : "Google.com",
    "timeout": 5000,
    "proto" : "https://"
}
```

**Comment by alfg** [comment]
Could be a possibility for the future if there are more options to warrant passing an object as a parameter. For now, just keeping it simple with source defining the optional proto/host/port.

#10
