### ISSUE TITLE
Response time different.

### ISSUE THREAD

**Issue by ibrahimince** [alfg/ping.js#12]
May I please ask why response time different when I use cmd in my computer compared to browser.

I do get 10ms when i ping to am.guildbit.com while i do get around 200 when i ping from my browser.
Thank you.

**Comment by alfg** [comment]
The response time for this project is more of a representation of a browser network request, compared to a native ping (ICMP) from the OS. I noted this on https://github.com/alfg/ping.js#notes.

However, just doing a quick test, I get the following results:

```
$ ping am.guildbit.com
PING am.guildbit.com (178.62.248.252): 56 data bytes
64 bytes from 178.62.248.252: icmp_seq=0 ttl=53 time=141.421 ms
64 bytes from 178.62.248.252: icmp_seq=1 ttl=53 time=141.322 ms
64 bytes from 178.62.248.252: icmp_seq=2 ttl=53 time=141.159 ms
64 bytes from 178.62.248.252: icmp_seq=3 ttl=53 time=141.324 ms
```

and using http://jsfiddle.net/alfg/sr0tpn4x/:

```
guildbit.com 48
sf.guildbit.com (SFO) 24
ny.guildbit.com (NYC) 87
am.guildbit.com (AMS) 153
```

Seems to be pretty close, but not completely accurate. So I'm sure results will vary.
