### ISSUE TITLE
code still seems to return requests on timeout

### ISSUE THREAD

**Issue by mbariola** [alfg/ping.js#18]
while testing the timeouts, it seemed to me that even if the timeout is hit, you will still get the result of call when it happens (i.e. if you put a timeout of 300ms and the call requires 330ms, you would get a "timeout" result (error fixed in my PR) at 300ms but also the result of the original call at 330ms, whether OK or an http error. Is there any way to discard such "late" running request? I have not extensively tested this but am somewhat concerned about memory pileup if it happens too often with regards to the frequency of the pings

**Comment by alfg** [comment]
Hi @mbariola. 

Thanks for the PR and taking the time to contribute! I added 2 comments on the PR if you can check those out. 

Also, I'm not sure if a way to discard late running requests, but open to recommendations. :)

Thanks!

**Comment by alfg** [comment]
Closing per comments on: https://github.com/alfg/ping.js/pull/17

Feel free to reopen if the comments in the PR are addressed. Thanks!
