### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Scothosts** [alfg/ping.js#20]
Every time I try this with a known web address it returns Error.

**Comment by alfg** [comment]
Hi @Scothosts, 

Since this module uses a method of loading an image (favicon.ico by default), it will return an error along with the ping if the image doesn't exist. This was put in place by https://github.com/alfg/ping.js/pull/15. 

https://github.com/alfg/ping.js#notes

**Comment by Scothosts** [comment]
Ah ok, I was actually looking for a client side script that could ping a server which doesn't have web pages, so I don't think this will work. Even if I listen for the error and time the reply this won't differentiate between a dead server and the running server which doesn't have a favicon.ico

**Comment by alfg** [comment]
Yes, that's correct. There's no native browser/JS api to do a "ping", so this is more of a hack to load an image over http only to simulate a ping.
