### ISSUE TITLE
How to import this package in Javascript(React Js)?

### ISSUE THREAD

**Issue by ajits731** [alfg/ping.js#21]

**Comment by alfg** [comment]
Hi @ajits731,

Currently, you can only use this module by loading the `dist/ping.js` file:
```
<script src="dist/ping.min.js"></script>
```

and the `Ping` module will be available globally.

I'll look into making this into a proper npm module soon, so that you can import through a module bundler.

**Comment by alfg** [comment]
Hi @ajits731,

This is now fixed with https://github.com/alfg/ping.js/pull/22.

See react example here:
https://github.com/alfg/ping.js/tree/master/demo/react-example
