### ISSUE TITLE
How to ping proxy server?

### ISSUE THREAD

**Issue by rana01645** [alfg/ping.js#26]
First of all thanks for this great library :D 

Is there any way to ping proxy server ??
When I ping ip from the command line its working 
But showing error in this library
For instnace how can I ping this proxy below?
24.154.112.20:8080

**Comment by alfg** [comment]
Hi @rana01645, 

I'm not sure if this would work since this library basically tries to load an image over http to get the response time. I don't think there's any way around this since it assumes an http endpoint.
