### ISSUE TITLE
ping.js   i  find  a  bug  why  request time  first  is  lower  than   next time   have so  big  distance  

### ISSUE THREAD

**Issue by yehoan** [alfg/ping.js#27]
i  find the 
![image](https://user-images.githubusercontent.com/22631753/54604816-af5fb600-4a82-11e9-9cf6-ee88e6dc3a28.png)  the  request  time  have  big  distance   i  am  just  want  to know  the  reason

**Comment by yehoan** [comment]
first time   maybe  need  500ms  but  next  time  when  i  send  the  function  again  it  is only   need   75ms

**Comment by alfg** [comment]
Hi @yehoan,

Sorry for the late response.

Similar to #12. The response times can vary since it's more of a representation of a browser network request, compared to a native ping (ICMP) from the OS. It is susceptible to caching, timeouts, etc... on the server side.
