### ISSUE TITLE
Ping Lib is not recognized

### ISSUE THREAD

**Issue by venmathis** [alfg/ping.js#29]
I did installed the ping library and I tried to import and use the same. But when I import it is not being accepted and shows the following error on hover.

![image](https://user-images.githubusercontent.com/40182461/56836031-8679d000-683b-11e9-8a5a-03c4710d2437.png)

```
Could not find a declaration file for module 'ping.js'. 'c:/Users/vn509wj/Desktop/workspace/ui-retaillink-react/node_modules/ping.js/index.js' implicitly has an 'any' type.
  Try `npm install @types/ping.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'ping.js';`ts(7016)
Could not find a declaration file for module 'ping.js'. 'c:/Users/vn509wj/Desktop/workspace/ui-retaillink-react/node_modules/ping.js/index.js' implicitly has an 'any' type.
```

**Below is the module and plugin in my web pack**
``plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new CopyWebpackPlugin([
      { from: 'src/libs/js', to: 'vendor/d3'}
    ]),
    new CopyWebpackPlugin([
      {from: 'src/custom', to: 'vendor/custom'}
    ]),
    new HtmlWebpackIncludeAssetsPlugin({
      assets: ['vendor/d3/d3.v3.min.js','vendor/d3/d3.tip.v0.6.3.js'],
      append: false,
      publicPath: 'rl-portal/'
    })

  ],
  module: {
    loaders: [
      {test: /\.d\.ts$/, include: path.join(__dirname, 'src'), loader: 'babel', query: { plugins: ['transform-decorators-legacy'], presets: 'es2015'}},
      {test: /\.js$/, include: path.join(__dirname, 'src'), loader: 'babel', query: { plugins: ['transform-decorators-legacy'], presets: 'es2015'}},
      {test: /\.jsx?$/, loader: 'babel', exclude: /node_modules/, query: { plugins: ['transform-decorators-legacy', 'transform-es2015-destructuring', 'transform-object-rest-spread'], presets: ['es2015', 'react']}},
      {test: /(\.css)$/, loaders: ['style', 'css?sourceMap']},
      {test: /\.less$/, loader: "style!css!less"},
      {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=100000&mimetype=file"},
      {test: /\.(woff|woff2)$/, loader: "url?prefix=font/&limit=50000"},
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=20000&mimetype=application/octet-stream&name=fonts/[hash].[ext]"},
      {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml&name=images/[hash].[ext]"},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.(png|jpg|gif)$/,loader: 'url?limit=25000&name=images/[hash].[ext]'},
      {test: /\.pdf$/,loader: 'file?name=[name].[ext]'}
    ]
  },``

**Comment by alfg** [comment]
Is this a Typescript warning? I don't currently use Typescript or have any type declarations in this project.
