### ISSUE TITLE
what if ping fails

### ISSUE THREAD

**Issue by ndubbaka** [alfg/ping.js#3]
what if ping fails, like pinging youtube.com from china?
does callback function always get response time and not status or error code?

**Comment by alfg** [comment]
Hi @ndubbaka,

I believe it'll eventually return the response time, and not an error code as the code tests the "ping" by loading an image that most likely doesn't exist, so the http response code will vary. However, I think the response time can timeout depending on the browser being used. 

I tried testing by loading `192.168.1.225` which seems to timeout at approximately 20 seconds in Chrome and Firefox, but times out at 7 seconds in IE10. 

http://jsfiddle.net/sjf42e7u/

If you have any examples you can try adding to the snippet above and see how the results are displayed.

**Comment by ndubbaka** [comment]
Thanks @alfg,
For time being I am going with https://github.com/jdfreder/pingjs

**Comment by alfg** [comment]
You're welcome. Good luck!

**Comment by roynasser** [comment]
Sorry but arent these two just http response checkers?  Ping is a network term using icmp packets to determine if a server is up/responding (ponging back).... checking a http response is nothing to do with "ping" per se...

**Comment by alfg** [comment]
@RVN-BR Right. Javascript (in the browser) doesn't support a native ping, of course. So it's just a general term to make it easier to search for a package with similar functionality.

**Comment by roynasser** [comment]
Understood... still should be a bit clear that this a "http ping" or "http alive check"...

It took me a few seconds studying the code to get to that... I was actually looking for some icmp option (i'm aware JS doesnt support it, but who knows what kind of crazy stuff someone can come out with...)

anyways, its fine for an http check, i just found these two projects quite misleading as they dont even mention HTTP... :/ Ping is Ping LOL

Useful nonetheless, in other use casees

**Comment by alfg** [comment]
I hear ya! I have a disclaimer in the readme, but I can probably make it a bit more clear. :)

**Comment by roynasser** [comment]
Hhaha no worries... I'm going to be using it anyways on my project, but just as a different use :)
