### ISSUE TITLE
ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by Hazza88** [alfg/ping.js#35]
I get the error "ReferenceError: Image is not defined" when trying to start it, here is the code: 

const Ping = require('ping.js');
var p = new Ping();

p.ping('https://github.com', function(err, data) {
  if (err) {
    console.log('error loading resource');
    data = data + ' ' + err;
  } else {
    console.log(data);
  }
});

**Comment by alfg** [comment]
Are you running this in Node.js by any chance?

**Comment by Hazza88** [comment]
> Are you running this in Node.js by any chance?

Yea I am

**Comment by alfg** [comment]
Ah, yeah this module is for the browser.

I've updated the README to clarify.
