### ISSUE TITLE
How would i change the favicon image and how would i ping a minecraft server

### ISSUE THREAD

**Issue by devramsean0** [alfg/ping.js#37]
title really says it all tbh

**Comment by alfg** [comment]
Hey @devramsean0, 

You can set the favicon property in the options object to point to another favicon url if provided:
https://github.com/alfg/ping.js#pingoptions

You can only "ping" an HTTP endpoint. So the server would need to have an HTTP server of some sort for `ping.js` to get an idea of the response time.
