### ISSUE TITLE
Response times are not correct

### ISSUE THREAD

**Issue by Grrby** [alfg/ping.js#38]
Hi,

Response times given by ping.js are totally different then from real ping. 
For example:
google.com cmd ping 28ms vs ping.js 385ms 
my router cmd ping 1-2 ms vs ping.js 1 -21ms (looks like random numbers)
I like idea of this script but actually something is wrong, make it almost useless.

**Comment by alfg** [comment]
The response time for this project is more of a representation of a browser network request, compared to a native ping (ICMP) from the OS. 

I noted this on https://github.com/alfg/ping.js#notes. So results will vary.

**Comment by alfg** [comment]
#12

**Comment by Grrby** [comment]
Thank you for quick answer. I see.
Anyway results are not even close to ICMP ping and what is worst they are not stable. When I ping some local host, for example router, answers are in range from 1 to 28...

**Comment by alfg** [comment]
Yeah, it really depends on the http server that is giving the response and it will vary. For example, caching will affect the performance drastically. It works fine for my use case and gives me a rough idea of the http server's latency.
