### ISSUE TITLE
SSL support 

### ISSUE THREAD

**Issue by jonatanolsson** [alfg/ping.js#6]
Like this tool ! 

Had problems with HTTPS request that did not work for me so i added a new function arg (secure) and edited a bit of the src stuff

And this works great

line15

```
Ping.prototype.ping = function(source, callback, secure) {
```

line 32

```
this.img.src = ((secure) ? "https://":"//") + source + "/?" + (+new Date()); // Trigger image load with cache buster
```

**Comment by alfg** [comment]
Hi @jonatanolsson, 

Thanks for the suggestion! I was also thinking instead of adding the extra `secure` flag, we can just adjust the source argument so it accepts the protocol + domain. For example:

```
var p = new Ping();
p.ping("https://google.com", cb);
```

Of course, with a fallback to http if the protocol isn't provided. 

Thoughts?

**Comment by EldonMcGuinness** [comment]
For what it is worth, if a secure option is to be added, perhaps a port option should be as well. This will help to ping webservers that are on non standard ports.

---

--EDIT--
Added PR #10 to address this, you can see it in action on [jsfiddle](https://jsfiddle.net/EldonMcGuinness/uko8fmye/)

**Comment by alfg** [comment]
#11 #10
