### ISSUE TITLE
Not working if browser not have internet connection

### ISSUE THREAD

**Issue by Galathius** [alfg/ping.js#7]
Ping callback also triggering if net::\* error occured.
![image](https://cloud.githubusercontent.com/assets/5315954/11515022/9e76a7a0-988c-11e5-963c-56dda04925cc.png)

**Comment by EricTiger1986** [comment]
+1
This issue occurs in Chrome.

**Comment by alfg** [comment]
https://github.com/alfg/ping.js/pull/15
